name: Generate Documentation
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: erikyo/tsdoc-action@v1
        with:
          source_dir: ./*
          output_dir: ./docs
          front_page: README.md
